### PR TITLE
Network freq udp

### PR DESCRIPTION
**Pull request by aa5sh**
Added an option for a new Network Notification for current Frequency.  I can then consume it with other applications.

### CODE REVIEW

**Comment by foldynl** [comment]
I would like to see something more general here than just the frequency. I will try to change it to general information about the state of the rig.

**Comment by aa5sh** [comment]
I was thinking that as well but all I really had a need for was just
frequency, wanted to keep it simple initially.

**Comment by aa5sh** [comment]
I've been thinking more on this.  But what I think would be usefull would be a bit more information on the current status much the same as WSJTX.  Maybe the current callsign, country, dxcc, heading etc.  That way if someone wants to monitor the UDP with another application and take actions they can.  I had something similar working with RumLog to my app that controls my steppir, spe amplifier, rotor and webswitch.

**Comment by foldynl** [comment]
I just wanted to create something that would provide information about all the parameters of the rig—not just the frequency, but also the mode, power, and others. The QSO is unrelated to this, as it is handled in a different message.

**Comment by foldynl** [comment]
just for info. I plan to rework the Network notification service. It should be based on Websocket. UDP Notifications will be declared obsolete and removed over time. The new Websocket Server will be able to provide more information about what is happening in qlog. Among the new notifications will be Rig status. I would like to see it in version 0.42 or 0.43.

**Comment by aa5sh** [comment]
Thanks I deleted this branch on accident last night.  I was thinking about it again and was going to add more info like you mentioned.  I was making test ones and got confused.  But I agree WSS would be a good solution.  I picked up a used Kenwood TS-990 for a very good deal, but now my radio is much removed from my Steppir controller, so was wanting a way to have it track since they are different rooms in the house.  That is what started me wanting it before as well, being able to easily use different radios and have my Steppir follow correctly.

**Pull request closed without merging**
