### PR TITLE
update Chinese translation to v0.33.0

### PR DESCRIPTION
**Pull request by BG7JAF**
I have update the Chinese translation to v0.32.0.
Because I upload the ts file to crowdin.com to do the translation, so maybe the file's indent is not like before.

### CODE REVIEW

**Comment by foldynl** [comment]
Thank you. It will be a part of the next release. Unfortunately, I am not able to verify the quality of the translation provided by crowdin.com – I have to trust you to verify it before generating the PR.

**Comment by foldynl** [comment]
I have implemented #322 in the testing_0.33 branch. Could you please update your transaction against this branch? This PR is already included there, so your work won't be lost.

**Comment by BG7JAF** [comment]
> I have implemented #322 in the testing_0.33 branch. Could you please update your transaction against this branch? This PR is already included there, so your work won't be lost.

Glad to hear that. I'll update the translation and re-upload it.
73

**Comment by foldynl** [comment]
Thanks. there are many conflicts with your previous PR (indentation problem), so I couldn't do a direct merge. Therefore I had to replace the file and it seems that the translation file is valid again. Translation file is a part of testing_0.33 branch now.

**Pull request closed without merging**
