### PR TITLE
Awards

### PR DESCRIPTION
**Pull request by aa5sh**
Added simple stats similar to IOTA for POTA Hunter, POTA Activator, SOTA and WWFF

### CODE REVIEW

**Comment by foldynl** [comment]
Thanks. 

I want to be sure of one thing. For example, according to the WWFF rules, statistics should be calculated with respect to the callsign. it means if I have WWFF ref A for callsign OK1AAA, and WWFF ref B for callsign OK1AAB, then they are two different callsign and WWFF should be calculated for both callsigns separately. It is so? 

From WWFF rules:
```
Activities can be undertaken with multiple operators using a group callsign. In
that case all QSOs made are awarded to the group callsign. Individual operators
can claim QSOs as well, but only the ones they actually made themselves.
Claiming QSOs as an operator in this situation requires specifying both the group
callsign and the relevant operator callsign in the ADIF file for each QSO.
```

Based on this chapter, I conclude that the statistics should be calculated per callsign, right ?

in view of the fact that your change calculates statistics through all callsigns in the log (the log can contain different My Callsigns), so this change will not calculate the statistics correctly. In the case of current statistics, statistics are based on DXCC Entity. In the case of WWFF and others, it should be calculated on the basis of Callsign. Am I wrong ?

Isn't this the case for POTA and SOTA?

**Comment by aa5sh** [comment]
The best way I could think to support this was to add a new combo box that lists all the station callsigns in the log table.  Then it can be used in the filter for those awards.

**Comment by foldynl** [comment]
I'm sorry, but I have to stop you. There are a few modifications I had to make

1) callsign. Sorry, bad decision. Despite the fact that POTA etc. are related to callsign, it will be better to do statistics without callsign. The problem is that the same callsigns are SP/OK1AAA and OK1AAA and OK1AAA/P. so you can't use simple `=`. It is already solved several times within QLog, but "base callsign" is calculated for `contact.callsign`. Not for `contact.my_callsign` . However, this assumption complicates the situation. So it will be better if the statistics are calculated across the entire DB. Sorry I changed my mind.

2) I took your first commit and started editing it. Unfortunately, there were a few things missing. It's not only about what you added, but also about the double-click etc. Then I edited some other parts there. So I have a new branch for it.

3) And now the main thing. I see your commits where POTA/SOTA/WWFF are divided. I also came across this and am currently implementing it. However, there are a few things to think about.
    - it is not allowed to have a List of Values ​​for SOTA/WWFF. Therefore, it is not necessary to solve this. However, it must be verified in the QLog's input field that more items cannot be entered for SOTA a WWFF.
    - it is allowed for POTA. Unfortunately, there is another problem. It is necessary to solve cases of the type K-4562@US-CA, where it is not possible to compare `pota_directory = contact.pota_ref`. 

4) it is necessary to solve the performance, because for large databases the search will be slow.

Thanks for the PR, I think I know what you want and I'll try to finish it somehow.

**Comment by aa5sh** [comment]
Ok I’ll stop looking at it and honestly you don’t need to spend any time on it for me.  I was just trying to help you.  I had looked at the issues page for items that maybe I could help with but I don’t want to cause you more unnecessary  work.  I don’t really have a use case for it for me.  But I saw another OM wanted it.  Main thing I wanted to try and hopefully save was it working/building on a MacOS.

**Comment by aa5sh** [comment]
Do you want me to jus cancel the PR?

**Comment by foldynl** [comment]
Sorry, I wrote that poorly. Sometimes I don't use the right words. I'm glad you started implementing it, but I noticed that the design of the entire Dialog needs to be changed to correctly implement POTA and SOTA. Therefore, I took your original commit and started reworking the dialog. I also added functions from your other commits. However, I had to adjust a lot of things around it. I had to tweak and optimize the SQL a bit.

Another thing I modified is that while POTA is defined in the ADIF List of POTA, SOTA and WWFF are not. However, there is a POTA@xxx notification defined in the database, which I had to resolve in terms of performance.

So, thank you very much for your commits. They have all been implemented in the new branch `AwardsPOTASOTAWWFF`, just with a new arrangement. I hope, it should now be easier to add new statistics.

Please, do not cancel the PR. It is good job. Please, verify the `AwardsPOTASOTAWWFF` branch if it is OK from your perspective. there is still a need to make some DB changes, but I have to make them just before closing the release.

**Comment by aa5sh** [comment]
It looks good to me.  I like the changes you made the SQL queries.  I struggled with the best way to handle to GUI so it made sense as well.  I played with several options.

Thanks

Michael

**Comment by foldynl** [comment]
PR is part of v0.38

**Pull request closed without merging**
