### PR TITLE
Feature/86 online map error on no network

### LINKED ISSUE #86: Online Map - Uncaught TypeError when network is unreachable
10:17:34.598 [CRITICAL][js]	=> Uncaught TypeError: L.terminator is not a function [(null):qrc:/res/map/onlinemap.html:48] 
10:17:34.681 [CRITICAL][js]	=> Uncaught TypeError: Cannot read property 'createIcon' of undefined [(null):qrc:/res/map/onlinemap.html:5] 
10:17:41.383 [CRITICAL][js]	=> Uncaught TypeError: L.terminator is not a function [(null):qrc:/res/map/onlinemap.html:48] 
10:17:41.441 [CRITICAL][js]	=> Uncaught TypeError: Cannot read property 'createIcon' of undefined [(null):qrc:/res/map/onlinemap.html:5]

### PR DESCRIPTION
**Pull request by pulponair**
Refactor OnlineMap to module Pattern and and offline handler and auto online detection.
Resolves #86

### CODE REVIEW

**Comment by pulponair** [comment]
@foldynl 
Ok my bad. I didnt't test it within the qt webview. I did a quick shot within the browser. Probably the webview. 
Give me some more time to look into that. I play around with it a little more.

Regarding the QWebEnginePage i need to do some research for alternatives. I don't use QT nor do i use c++ regulary so i am pretty rusty. Just let me dive into that a little deeper.

**Comment by pulponair** [comment]
@foldynl 
ok i took a brief look. 
Proposal:
Remove all Javascript logic from the QT code. Instead add Methods to the map object handling the logic and from QT just call this public "API" and pass the needed parameters. 

I can do that even the QT part i think. I just need some time ok?

**Comment by pulponair** [comment]
@foldynl 
I did some research last night. 

First of all: I am not super sure if use a "WebPageView" is the way to go. For the following reasons:
1. As mentioned by you it does fully work plattform independend.
2. From a Javascript point of view it does not seem to support elementary things like "navigator.onLine" etc. I experiencend similar issues with webviews on mobile devices. They don't show consistent behavior across plattforms and their behavior changes quite often.
But for now i will follow that webPage route and see where it goes to. T

he reason why my code is failing is the fact, that the online status is always true within the webPageView :). Actually it is supposed to work like this:
Check online status -> if online, load assets, create map. if not online, wait for online and then load assets and create map.
I'll find a workarround and refactor the JS to have an an api for QT to communicate with "addNewWorkedGrid(lat,long) etc".

I also read about qml and the map/location plugin. Actually that looks pretty clean. But i have to admit, that i ve almost no expericences with QT. 

And i wanted to ask you if you are avaible for a quick call maybe to give me a hand on a few "best practices" questions i have and give me an idea about what you think the map should be capable of in the future. That would enormously speed up my productivity because atm i am walking arround a little blind. :)

**Comment by foldynl** [comment]
> I also read about qml and the map/location plugin. Actually that looks pretty clean. But i have to admit, that i ve almost no expericences with QT.

the same situation is in my case. I just read about it, but experience is missing. But redesign of the map is more "nice-to-have" than "must-have" project at this moment. 

I am planning from release to release - a long term planning is missing. 
The upcoming release plan is available https://github.com/foldynl/QLog/projects/16 - it may vary. 
Ideas for the future releases are available https://github.com/foldynl/QLog/projects/5, 
Bugfixes are solved as soon as possible - there is no plan. 

> And i wanted to ask you if you are avaible for a quick call maybe to give me a hand on a few "best practices" questions i have and give me an idea about what you think the map should be capable of in the future. That would enormously speed up my productivity because atm i am walking arround a little blind. :)

**In general, my plans are:**
- make map as portable and easy as possible.
- easily expandable
- currently, the map is used in following widgets - the Main Widget, Statistics Widget, QSO Detail Widget (details below) and I have no plan to introduce a new map functionality now.

1) Main Widget (Online Map Widget). The implemented functions are
-  switch theme based on light/dark mode https://github.com/foldynl/QLog/blob/master/ui/OnlineMapWidget.cpp#L80
- draw a path https://github.com/foldynl/QLog/blob/master/ui/OnlineMapWidget.cpp#L31

2) Statistic Widget
- switch theme based on light/dark mode https://github.com/foldynl/QLog/blob/master/ui/StatisticsWidget.cpp#L437
- draw my locations based on database information https://github.com/foldynl/QLog/blob/master/ui/StatisticsWidget.cpp#L579
- draw DXs based on database information https://github.com/foldynl/QLog/blob/master/ui/StatisticsWidget.cpp#L623
- colored grids based on worked/confirmed https://github.com/foldynl/QLog/blob/master/ui/StatisticsWidget.cpp#L666

3) QSO Detail Widget
- switch theme based on light/dark mode https://github.com/foldynl/QLog/blob/master/ui/QSODetailDialog.cpp#L795
- draw DX based on database information https://github.com/foldynl/QLog/blob/master/ui/QSODetailDialog.cpp#L1013
- draw my location for the QSO https://github.com/foldynl/QLog/blob/master/ui/QSODetailDialog.cpp#L1059

Currently, there is no API between map and application. In general, you can find all functionalities by searching a function `runJavaScript`. I call this function when I need to do something in the map.

**What I expect from map**
- map must be prepared to change Light/Dark Mode
- map must show  grayline
- maps must show grids (grids can be colored based on worked/confirmed)
- map can be able to show polyline (path)
- map must show points (Stations and my station location). Color icons depend on work/confirmed status.
- map must be prepare for network instability (network reconnection).

**What is welcomed (nice-to-have)**
- Grayline - the shadow will be gradual. something like https://pskreporter.info/pskmap.html
- any improvements

Call is possible but I do not know if I can help you via the call. if you find a call useful, send me an email present in the commits, what the best time for you is and what exactly you want to know. But I think that it is better to look at the source code. 

Keep in mind. I am a back-end programmer and this is my first touch with QT development. Many illogical things in the code may stem from my misunderstanding of QT.

**Comment by foldynl** [comment]
no modifications during more than a year. I am closing this PR

**Pull request closed without merging**
