### PR TITLE
Wsjt widget rr73

### PR DESCRIPTION
**Pull request by aa5sh**
I adjusted the Regex to not only account for decodes starting with CQ but also the entries ending in RR73, RRR or 73.

### CODE REVIEW

**Comment by foldynl** [comment]
What's the motivation for implementing this? 
Currently, QLog shows stations that send CQ and then track them. Why include stations that send 73 in this list?

**Comment by aa5sh** [comment]
When I operate the FTx modes I always consider someone sending 73 as available to be called much like someone calling CQ.  At times DX stations will be working stations consecutively and may go a bit before calling CQ.  Just gets them in the list quicker.

**Comment by foldynl** [comment]
I tested it for a while, and it seems to me that there are a few "unwanted" things. Originally, the QLog WSJT widget was designed as a tracker for stations calling CQ— stations want to start a QSO. I have no problem extending it to track with a different condition, but your modification has a side effect that I noticed during my tests. I see stations that are more likely to be in S&P (Search & Pounce) mode on the band. This results in two things:

1) The WSJTX widget is more populated.
2) For these stations, gridsquare, distance, etc., are not displayed because RR73 does not include a gridsquare.

So, my observation is that a station sending RR73 is not necessarily a station I can call later, as it might be in S&P mode.

Is my assumption incorrect, or did I overlook something?

**Comment by aa5sh** [comment]
You are correct in 1 and 2.  There are going to be more stations and the
gridsquare and all will not be there.  I guess it is personal preference.
When I am working the FTx modes if there is a station I want to work and I
see them send RR73 or 73 I will call them.  I don't wait to see them call
CQ.  Sometimes I see stations calling stations back to back and never call
CQ.  It is not a big deal if you don't want to add more stations.  I just
like to have possibility of getting a station I want/need that may not be
calling CQ.

**Comment by foldynl** [comment]
The question is whether this is the right approach. I don't want to say that it's wrong in the case of expeditions, where there's a huge pile-up, but in the case of "normal" callsigns, it could be unintended, especially when the station is operating S&P (Search and Pounce). It's happened to me several times that someone contacted me in this way when I intended to switch to a different callsign after finishing a QSO. I really don't know if it's a good idea.

**Comment by aa5sh** [comment]
Ok that’s fine it is just personal opinion.  I will go in and cancel the PR.  Not a big deal.

**Comment by foldynl** [comment]
This is not my rejection of the idea because it’s wrong. I'm just looking for arguments for and against it. Another issue against it is that with RR73, the QSO Filter doesn’t work well because the gridsquare is unknown (QSO Distance Filter). So it is showing QSOs that don’t meet the filter criteria. Maybe we can find something that will also meet your requirement.

**Comment by aa5sh** [comment]
Honestly I don’t know at this point if it was really accomplishing what I wanted.  I’m still getting my understanding of how thing interoperate.  At the end the day what I was hoping for any transmitting stations callsign/dxcc be available to alert me to he is transmitting.  I would like to know if a certain country is working people and be alerted to it.  I honestly don’t want to have that WSJT-x window visible but would like to know when a new one is working stations.  

I haven’t spent enough time wrapping my head around the alert functionality yet, but it appears currently it would only trigger on the CQ stations, but I could be wrong.  I just would like that extended.

**Pull request closed without merging**
