### PR TITLE
Updated German Translation

### PR DESCRIPTION
**Pull request by dl2ki**
First QLog Pull Request .

### CODE REVIEW

**Comment by foldynl** [comment]
Thank you. It will be merged as soon as possible.

**Comment by dl2ki** [comment]
Edited with "QT6-Linguist".

- Terms that are part of common language usage have not been translated. e.g. rig, spot, callbook, operator, greetings, ....
- Also e.g. interface parameters and similar fixed terms.
- Individual terms have not been translated because a suitable term / abbreviation has not yet been found.

Not translated terms remain marked as "Not accepted" in "QT Linguist".

Verification of translation in real program environment required.

Consideration should be given to outsourcing the language files externally.

**Comment by foldynl** [comment]
squashed and merged. It is a part of testing_0.20 branch now. Thank you.

**Comment by foldynl** [comment]
A part of v0.20

**Pull request closed without merging**
