### PR TITLE
Mac os deployment

### PR DESCRIPTION
**Pull request by aa5sh**
This should fix the MacOS Deployment.  For some reason the TAG thing is throwing me off in my fork so I hard coded the version but that should be able to be changed back.  I need to just make a simple action and figure out what I need to do.

### CODE REVIEW

**Comment by foldynl** [comment]
Thank you. I have accepted only the first commit. Could you please explain why you are deleting MacOS 13 in the second commit? Unfortunately, the third commit cannot be accepted because it is version-dependent. How can I prepare the next version? I would have to edit this file for each version.

**Comment by aa5sh** [comment]
For the macos 12/13, for some reason it would fail if in my fork if it ran
both so I just dropped one.  I never looked deep into why it was.

I thought I had mentioned about the version but for some reason it wasn't
grabbing the tag version for me.  I am 99% sure it is just something in my
process to generate the job.  I am new to github.  So I don't know the
proper steps.  for that last commit just take out the hard comment and put
like you had the tag code.  I will try and read the steps, like do I need
to generate a release with the appropriate tag before running the option?

**Comment by aa5sh** [comment]
I figured out how to do the tag so it flows in.  I cleaned it up a little bit (not sure why those files were being copied).  I just did a test run on branch and it seems to work fine.  I updated the file on my branch but not 100% sure it updated the pull request but here is the code I was using: 
`
name: macOS deployment

#on: [push, pull_request]

on:
  workflow_dispatch:
  push:
     branches:
       - master

jobs:
  macos-build:
     name: MacOS Build
     strategy:
       matrix:
         os: [macos-13]

     runs-on: ${{ matrix.os }}

     steps:
     - name: Install Dependencies
       run: |
         unset HOMEBREW_NO_INSTALL_FROM_API
         brew update
         brew upgrade || true
         brew install qt6
         brew link qt6 --force
         brew install hamlib
         brew link hamlib --force
         brew install qtkeychain
         brew install dbus-glib
         brew install brotli
         brew install icu4c
         brew install pkg-config
     - name: Checkout Code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
         submodules: recursive
     - name: Get version from tag
       run : |
         TAGVERSION=$(git describe --tags)
         echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV

     - name: Configure and compile
       run: |
         mkdir build
         cd build
         qmake -config release ..
         make -j4
     - name: Build dmg
       run: |
         cd build
         macdeployqt qlog.app -executable=./qlog.app/Contents/MacOS/qlog 
         macdeployqt qlog.app -dmg
     - name: Copy artifact
       uses: actions/upload-artifact@v4
       with:
         name: QLog-${{ env.TAGVERSION }}-${{ matrix.os }}
         path: /Users/runner/work/QLog/QLog/build/qlog.dmg
`

**Comment by foldynl** [comment]
PR is part of v0.38

**Pull request closed without merging**
